### ISSUE TITLE
No antiaffinity by default.

### ISSUE THREAD

**Issue by KnicKnic** [Azure/aad-pod-identity#1058]
**Describe the bug**
deployed via helm

**Additional context**
I would have expected antiaffinity rules to be set so that each version of the aad-pod-identity-mic would be on different nodes.
You should probably model this after coredns's antiaffinity settings in AKS.

If both instances end up on the same node and that node dies, we will be subject to the default eviction threshold. I do not want to wait minutes for a replacement controller to come up.

**Comment by aramase** [comment]
@KnicKnic Are you interested in opening a PR to add the anti-affinity spec for MIC deployment?

**Comment by JasonWhall** [comment]
👋 I'm happy to contribute this, however I would just like to clarify a couple of things before adding default rules as this could produce a breaking change to existing users.

- @KnicKnic - You mention to model this on CoreDNS in AKS, however the default coredns chart [does not specify affinity rules by default](https://github.com/coredns/helm/tree/master/stable/coredns) This likely means the affinity rules are set by the AKS implementation of this chart/manifests. Going by that logic, should the same be done only in AKS addon of pod identities and not in this chart?

- If we are to add a default `antiAffinity` rules, do we also want to retain the existing option of allowing the user to specify their own affinity rules, therefore overriding the default ones we will set? Do we also need to cater for amalgamating nodeAffinity or podAffinity specified by the user if they are only set?

**Comment by chewong** [comment]
Thanks for taking the initiative to contribute! Yes, we will allow the user to define their own custom affinity/anti-affinity rules. The option should be empty by default.

**Comment by KnicKnic** [comment]
@JasonWhall @chewong 
I disagree, I think the helm chart should setup reasonable production defaults. 
Why are we defaulting to 2 replicas, but not setting anti-affinity? 

My understanding is the purpose of creating 2 is so that they can handle failure for the other one. If both of the pods are put in the same fault domain I don't see the point of having 2. If one crashes it will quickly restart. The greatest use for 2 is if the fault domain fails.

Currently I am  not using the addon due to the limitation in the number of identities, and therefore using helm chart.

Please keep in mind how many of your customers have brought up the issue till now. Do you really expect those that haven't to know what to set as reasonable defaults?

**Comment by chewong** [comment]
That makes sense. @JasonWhall  please disregard my comment above since it looks like we already provide users the ability to define their affinity rules (https://github.com/Azure/aad-pod-identity/blob/master/charts/aad-pod-identity/values.yaml#L78-L88).

Regarding the default anti-affinity rules, our initial thought is to provide a minimal viable helm chart with mostly empty default values, similar to the coredns chart. I'd expect most users and cluster admins to leave the affinity value empty unless they really want fine-grained control on where pods should be scheduled. The best we can do is to provide a way for users to define their custom rule (which we did), but I am open to having a default value. @aramase what do you think?
