### ISSUE TITLE
Impersonating pod identity using labels?

### ISSUE THREAD

**Issue by omerlh** [Azure/aad-pod-identity#106]
First, this is a really good add-on, the missing piece between Azure and Kubernetes :)
If I understood the docs currently, each pod with the labels mentioned in the `Selector` field under identity binding will be able to request a token using MSI. Isn't that a security issue? Anyone with access to the cluster can deploy an app with the required label, and impersonate a pod.
After reading the docs, it seems that you can explicitly (maybe in the future?) to specify which pods to select. Is this in order to mitigate this threat?

**Comment by khenidak** [comment]
Anyone with access to the cluster already have access to assigned identities to the VMs. We have added namespace-ed identities to compartmentalize identities. 

Do you see another improvement we need to have?

**Comment by omerlh** [comment]
Maybe have a way to specify a deployment/replica set/service account?

**Comment by Schnerwitzki** [comment]
I just found this old issue, after I wondered exactly the same thing. Managed Identities would make it very easy to securly access Azure resources from your Pod. But I wonder how secure it actually is.

Imagine a scenario where you have a Kubernetes cluster with mutliple namespaces, controlled with RBAC. A user has only access to specific namespaces and his Azure resources.

The NMI is installed into kube-system, which can only be accessed by special administrators.

When you create an Identity resource you have to grant "Managed Identity Operator" role to the service principal the NMI is using. Which is fine, as you can trust it.

However in order to get the identity assigned, you only need to create a AzureIdentity resource, with the clientId and resourceId and an AzureIdentityBinding. The clientId and resourceId cannot be regarded as secret, as I suppose everybody with read access to the AAD tenant is able to resolve the clientId.

I don't see how declaring the AzureIdentity as "namespaced" would solve this. Couldn't someone create an identical AzureIdentity resource in his namespace? Maybe I'm missing something, please help me here. I would have excpected some secret configuration necessary inside my own namespace, which noone else is able to retrieve, in order to get the identity assigned.

**Comment by Schnerwitzki** [comment]
After talking to some very helpful experts from Microsoft, it seems at the moment the only way to make it secure, is to restrict the creation of AzureIdentity resources in Kubernetes to the ones who already control the NMI service (and hence the service principal which has the Managed Identity Operator role).

That's the way we're implementing it now. The teams who create an identity in some Azure resource group have to request the creation of the Azure Identity in their namespace from the operations team.

To automate this process, a colleague implemented a helpful operator service. You can find it here, if you like: https://github.com/webdevops/azure-msi-operator

**Comment by mblaschke** [comment]
Thanks @Schnerwitzki for mentioning the `azure-msi-operator`.
It's currently in development so feel free to try it. It's configurable so you can adapt it to your needs.
If something is missing let me know (Twitter, Slack, ...).
