### ISSUE TITLE
What is "--MICNamespace" for?

### ISSUE THREAD

**Issue by jhyot** [Azure/aad-pod-identity#1094]
I can't figure out what the NMI flag `--MICNamespace` is for. The documentation states: "MIC namespace to short circuit MIC token requests". What does "short circuit token requests" mean? Should I set this to the namespace where my MIC `Deployment` is located?

**Comment by chewong** [comment]
MIC requires an access token to perform operations such as assigning and unassigning identities from VM/VMSS on Azure. Since NMI intercepts all traffic to IMDS, the purpose of `--MICNamespace` is to allow MIC to fetch an access token without being intercepted by NMI. It looks like it's not commonly used anymore since we have https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/mic-exception.yaml, which does the same thing.

**Comment by jhyot** [comment]
Yes, it works for me without providing the `--MICNamespace`, even though I have deployed in a non-default namespace (I use the Exception resource).

So I guess this can be closed, unless you want to clarify that in the docs.

**Comment by chewong** [comment]
Let's close this issue for now since we'd recommend users to use the provided exception.
