### ISSUE TITLE
AAD integrated cluster with pod identity

### ISSUE THREAD

**Issue by rkoehl05** [Azure/aad-pod-identity#112]
I set up an AKS cluster with AAD integration as described here:

https://docs.microsoft.com/en-us/azure/aks/aad-integration

This allows us to secure manual administrator access to the cluster but we also need to allow a management process running in a pod on the cluster access to submit other pods to the cluster. We were looking to do this by running the management pod with a pod identity/MSI that has access to the cluster via AAD group. I setup pod identity as described here https://github.com/Azure/aad-pod-identity#deploy-the-azure-aad-identity-infra and hooked up my management pod with the AzureIdentityBinding. Within the pod I login as the identity and retrieve the kubeconfig for my cluster:

az login --identity
az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME

And then run a python script to submit the child pod to the cluster:

```
from kubernetes import client, config, watch

config.load_kube_config()
kub_client = client.CoreV1Api()

spec = {'apiVersion' : 'v1',
        'kind' : 'Pod',
        'metadata' : {'name' : 'testpod'},
        'spec' : {'containers' : [{'image' : 'ubuntu:16.04',
                                   'command' : ['/bin/bash', '-c', 'sleep 15m'],
                                   'name' : 'testcontainer'}]}}

kub_client.create_namespaced_pod('default', spec)
```
The create_namespaced_pod call fails with this error:

HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:anonymous\" cannot create pods in the namespace \"default\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}

Should we be able to non-interactively access a pod that has AAD integration enabled?

I tried the same setup on a cluster without AAD integration and the child pod is able to be submitted as expected utilizing the pod identity MSI.

**Comment by brendandburns** [comment]
The "system:anonymous" identity indicates that the code isn't correctly picking up your kubeconfig.

I have a couple of thoughts.

One, you might consider using Kubernetes Service Accounts:
https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/

Instead of an AAD identity.

If all you want to do is access the Kubernetes API (as opposed to other Azure resources) then that might be an easier path.

Second, when you run `get-credentials` you are getting a kubeconfig for _your_ identity, which is probably not what you want to use inside the Pod. You actually want to use Kubernetes RBAC to add the Pod MSI to your cluster's RBAC, and then use that identity inside the pod.

This route is definitely more complicated than using Kubernetes Service Accounts, but it will give you access to more than just the Kubernetes cluster.

**Comment by brendandburns** [comment]
Yes, pod identity will provide the MSI for the container if you follow the directions...

**Comment by rkoehl05** [comment]
Ok. That part of it is working. I am able to use the MSI attached to the pod to connect to the cluster via the get-credentials method and execute the child pod.

The error above occurs when AAD integration is enabled on the cluster. This does not seem to allow for any programmatic/non-interactive access to the cluster.

**Comment by brendandburns** [comment]
I don't think that aad-pod-identity can be used to access the Kubernetes API. @khenidak can confirm

The reason for this is that the AAD token is bound to an application ID and the app id for Azure is different than the App Id for the Kubernetes cluster.

To access the Kubernetes cluster, you probably really do want to use a Kubernetes service account as described above...

It's possible that I'm wrong, and you can use the AAD-pod-identity token, but in that case you will need to explicitly grab the token yourself and send it along to the kubernetes apiserver.

The kubernetes code doesn't know how to pull the AAD-container MSI.

Hope that helps.

**Comment by kkmsft** [comment]
@rkoehl05 - is this still an issue for you ?

**Comment by rkoehl05** [comment]
No I think we can close out
