### ISSUE TITLE
ManagedIdentityCredential authentication failed

### ISSUE THREAD

**Issue by omziv** [Azure/aad-pod-identity#1250]
We're trying to connect our storage account to MSI authentication. We've so far succeeded in creating the identity on our K8s cluster and assigning the permissions for that identity to the storage account.

However, when trying to access the storage with getToken function in the ManagedIdentityCredential class (in @azure/identity) I get the following error:

ManagedIdentityCredential authentication failed.(status code 404). More details: unknown_error(status code 404). More details: An unknown error has occurred. Response body: ManagedIdentityCredential - IMDS: Failed to retrieve IMDS token after 3 retries.

Is there a place to see a more detailed response body?
When does this error usually happen? Our identity is setup and doesn't show errors on K8s.

**Comment by aramase** [comment]
Here is our troubleshooting guide: https://azure.github.io/aad-pod-identity/docs/troubleshooting/#logging.

Could you check the logs for NMI pod running on the same node as your workload pod? The MIC logs should provide more information about the identity assignment success/failure.

**Comment by omziv** [comment]
I'm getting a response saying that no logs have been found:
![image](https://user-images.githubusercontent.com/80668253/155279283-2cbd1874-efd4-4e19-8e5f-7f73318086e0.png)

**Comment by omziv** [comment]
When trying to use a different namespace I get the following error (for nmi only, mic returns no results):
![image](https://user-images.githubusercontent.com/80668253/155279939-09872980-017e-46fa-889b-25830c56d939.png)

**Comment by adityajadhav95** [comment]
I'm getting the same error. Did anyone find the solution?

**Comment by elimisteve** [comment]
So am I. Also curious how to solve this issue, thanks.

**Comment by elimisteve** [comment]
@adityajadhav95 Solved it!

### Diagnosis

Thanks to setting the environment variable `AZURE_LOG_LEVEL=verbose` I was able to see that my backend JavaScript code was trying to talk to Azure's configuration service over http://169.254.169.254 . The Azure JS libraries assume that whatever is running on that IP is Azure. If there is no response, the code assumes that it itself must not be running on Azure, and then communicates with Azure's configuration service over some external URL.

**I was running this code on a hosting provider that has its own configuration service running at that same IP**, and it was returning a 404, leading my thinking-it's-talking-to-Azure JavaScript code to do the wrong thing!

### Solution

`sudo ufw insert 1 deny out from any to 169.254.169.254`

This makes the first UFW firewall rule one that denies any outbound traffic to 169.254.169.254 . This causes my JS to fail to talk to the non-Azure configuration service and talk to the _real_ Azure over the interwebs. Now everything works again! :tada:

(Turns out many hosting providers run a configuration service at that IP, so it was not smart for whoever wrote the Azure libraries to set `IMDS_ENDPOINT = "http://169.254.169.254/metadata/instance/compute/location"` without further checks that whatever replies from `169.254.169.254` is Azure...)
