### ISSUE TITLE
Client side throttling and performace issues

### ISSUE THREAD

**Issue by ondrejhlavacek** [Azure/aad-pod-identity#1267]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

We have a cluster with large fluctuation of pods. Hundreds of pods are created and deleted every hour and they use AAD Pod Identity. In the first minutes of every hour there seems to be a cleanup process that unassigns identites from deleted pods.

```
MIC

I0411 14:00:09.017538       1 mic.go:1040] processing node aks-***-vmss, add [0], del [173], update [0]
I0411 14:00:09.017573       1 crd.go:777] updating AzureAssignedIdentity default/*** status to Unassigned
... 20 more similar lines
I0411 14:00:15.385971       1 request.go:665] Waited for 4.365640692s due to client-side throttling, not priority and fairness, request: DELETE:https://10.1.0.1:443/apis/aadpodidentity.k8s.io/v1/namespaces/default/azureassignedidentities/****
... this repeats around 10 times

I0411 14:01:53.814183       1 mic.go:525] work done: true. Found 450 pods, 6 ids, 6 bindings
I0411 14:01:53.814205       1 mic.go:526] total work cycles: 137227, out of which work was done in: 29388
I0411 14:01:53.814212       1 stats.go:183] ** stats collected **
I0411 14:01:53.814216       1 stats.go:162] Pod listing: 608.845µs
I0411 14:01:53.814222       1 stats.go:162] AzureIdentity listing: 18.801µs
I0411 14:01:53.814226       1 stats.go:162] AzureIdentityBinding listing: 21.301µs
I0411 14:01:53.814230       1 stats.go:162] AzureAssignedIdentity listing: 1.852635ms
I0411 14:01:53.814234       1 stats.go:162] System: 2.700297ms
I0411 14:01:53.814238       1 stats.go:162] CacheSync: 14.001µs
I0411 14:01:53.814241       1 stats.go:162] Cloud provider GET: 0s
I0411 14:01:53.814245       1 stats.go:162] Cloud provider PATCH: 0s
I0411 14:01:53.814249       1 stats.go:162] AzureAssignedIdentity creation: 0s
I0411 14:01:53.814253       1 stats.go:162] AzureAssignedIdentity update: 0s
I0411 14:01:53.814255       1 stats.go:162] AzureAssignedIdentity deletion: 1m44.782904297s
I0411 14:01:53.814259       1 stats.go:170] Number of cloud provider PATCH: 0
I0411 14:01:53.814263       1 stats.go:170] Number of cloud provider GET: 0
I0411 14:01:53.814267       1 stats.go:170] Number of AzureAssignedIdentities created in this sync cycle: 0
I0411 14:01:53.814271       1 stats.go:170] Number of AzureAssignedIdentities updated in this sync cycle: 0
I0411 14:01:53.814275       1 stats.go:170] Number of AzureAssignedIdentities deleted in this sync cycle: 175
I0411 14:01:53.814279       1 stats.go:162] Find AzureAssignedIdentities to create: 1.200988ms
I0411 14:01:53.814283       1 stats.go:162] Find AzureAssignedIdentities to delete: 1.107281ms
I0411 14:01:53.814287       1 stats.go:162] Total time to assign or update AzureAssignedIdentities: 1m44.796634598s
I0411 14:01:53.814292       1 stats.go:162] Total: 1m44.811616091s
I0411 14:01:53.814296       1 stats.go:212] *********************
```

There are many throttling events that delay the process and it also seems that there was a single disruption around that time. 

```
NMI

E0411 14:01:51.445774       1 server.go:378] failed to get matching identities for pod: ***, error: getting assigned identities for pod *** in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I0411 14:01:51.445820       1 server.go:199] status (404) took 80335412893 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.14.0.89
```

However if I check MIC pod logs for errors there are none error logs for the particular log. I am aware these logs happened later than the error in NMI, but there are no other logs in NMI with the same pod/identity name. 

```
I0411 14:01:54.022193       1 crd.go:514] creating assigned id default/***
I0411 14:01:54.292721       1 crd.go:777] updating AzureAssignedIdentity default/*** status to Assigned
```

**Steps To Reproduce**

I don't know, we're seeeing this every hour though.

**Expected behavior**

No delays. Is there a way to trigger the "cleanup" more often, e. g. with every cycle? We have a lot of fluctuating pods (hundreds per hour).

**AAD Pod Identity version**

1.8.4

**Kubernetes version**

1.21.7

**Comment by ondrejhlavacek** [comment]
If the answer is to use https://azure.github.io/azure-workload-identity then my question would be what is the GA ETA?

**Comment by aramase** [comment]
> If the answer is to use https://azure.github.io/azure-workload-identity then my question would be what is the GA ETA?

@ondrejhlavacek The recommendation is start using Azure Workload Identity. This project is currently in maintenance mode and will only receive security patches and critical bug fixes. AAD currently only supports Azure AD Applications and they're working on supporting managed identity with workload identity. Once that's available we'll be able to provide a more concrete timeline for GA.

**Comment by ondrejhlavacek** [comment]
@aramase Unfortunately all identities we use in our applications are managed identities, so workload identity does not work for us at the moment. So I am still looking for a solution with AAD Pod Identity.

**Comment by se7enack** [comment]
This is some BS. Move to Azure Workload Identity is the solution? Fix the bug. You guys are the absolute worst. If I had my way we'd dump Azure and your awful support for literally any other cloud provider.

**Comment by aramase** [comment]
> This is some BS. Move to Azure Workload Identity is the solution? Fix the bug. You guys are the absolute worst. If I had my way we'd dump Azure and your awful support for literally any other cloud provider.

@se7enack could you provide more details on the bug you're referring to? Is it the same issue @ondrejhlavacek has posted here?

@ondrejhlavacek AAD Pod Identity in standard mode includes MIC and NMI with MIC performing the identity assignment when the first pod using the identity is created and unassigning when the last pod using the identity is deleted. The identity assignment typically takes ~40s and is a blocking operation. During this time, no other concurrent identity assignment operation can be performed on the VMSS. 

To avoid such identity assignment delays, you can run AAD Pod Identity in managed mode: https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/. In this mode, there is only NMI. The identities are manually assigned and hence there is no assignment/unassignment delay. Workloads will have access to the identity right when they're deployed and running. 

[Azure Workload Identity](https://github.com/Azure/azure-workload-identity) overcomes these limitations because it no longer requires components like MIC/NMI or the identity to be assigned to the cluster. We're encouraging users to try the new experience but are still fixing issues in AAD Pod Identity.

**Comment by ryanbradley7** [comment]
we are experiencing this same issue.  This has worked fine for us for the last ~2.5-3 years and suddenly stopped working this morning (maybe over the weekend but nobody was using it over the weekend).  We didn't change anything until after the issues started and we upgraded to v1.8.8 to see if that would fix the issue but it hasnt.

Our pods can not obtain an authorization token in order to retrieve secrets from keyvault.  This is preventing all of our development deployments and pipelines to fail.   

NMI logs (just a sample)
 nmi-j9h9l:E0419 17:12:46.008369       1 server.go:399] failed to get matching identities for pod: onedevqa/onedevqa-drop-cassandra-tables-kjt8p, error: clientID in request: 371f##### REDACTED #####0ef9, getting assigned identities for pod onedevqa/onedevqa-drop-cassandra-tables-kjt8p in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
 nmi-j9h9l:I0419 17:12:46.008437       1 server.go:213] status (404) took 80018725493 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.255.147.76

MIC logs:
 I0419 19:21:39.046769       1 request.go:665] Waited for 3.988716619s due to client-side throttling, not priority and fairness, request: PUT:https://10.0.0.1:443/apis/aadpodidentity.k8s.io/v1/namespaces/default/azureassig
 nedidentities/onedev3-batch-database-upgrade-xl9zr-onedev3-onedev3-identity


Any suggestions? Our development team is down because of this

**Comment by aramase** [comment]
> I0419 19:21:39.046769 1 request.go:665] Waited for 3.988716619s due to client-side throttling, not priority and fairness, request: PUT:[https://10.0.0.1:443/apis/aadpodidentity.k8s.io/v1/namespaces/default/azureassig](https://10.0.0.1/apis/aadpodidentity.k8s.io/v1/namespaces/default/azureassig)
nedidentities/onedev3-batch-database-upgrade-xl9zr-onedev3-onedev3-identity

@ryanbradley7 That log message is an information log from the client-go kubernetes library for the kube API request. It just shows how long the request took before it succeeded and doesn't indicate error.

Could you share the `AzureIdentity`, `AzureIdentityBinding` and pod yaml? Also, could you share the entire MIC logs? The relevant logs should be for the pod failing to acquire token  `onedevqa-drop-cassandra-tables-kjt8p`.

**Comment by ryanbradley7** [comment]
@aramase  there really arent any logs for the pods that are failing other than our generic "failed to obtain a token" message from some custom code we have.  This prevents the pods from starting up because the values from keyvault at required for initialization. This hasn't changed in years so it shouldn't be a problem.

Here is a sample log from our application

```
Apr 19 15:12:36 onedev1-idm-blue-6d67495479-cv8jm onedev1-idm-blue INFO Obtaining token for keyvault http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://vault.azure.net&client_id=<our_client_id>
Apr 19 15:13:56 onedev1-idm-blue-6d67495479-cv8jm onedev1-idm-blue INFO Response code 404
Apr 19 15:13:56 onedev1-idm-blue-6d67495479-cv8jm onedev1-idm-blue INFO Delaying before retry
Apr 19 15:15:21 onedev1-idm-blue-6d67495479-cv8jm onedev1-idm-blue INFO Response code 404
Apr 19 15:15:21 onedev1-idm-blue-6d67495479-cv8jm onedev1-idm-blue INFO Delaying before retry
Apr 19 15:17:06 onedev1-idm-blue-6d67495479-cv8jm onedev1-idm-blue INFO Response code 404
Apr 19 15:17:06 onedev1-idm-blue-6d67495479-cv8jm onedev1-idm-blue INFO Delaying before retry
Apr 19 15:17:11 onedev1-idm-blue-6d67495479-cv8jm onedev1-idm-blue FATAL Could not obtain token,  Response code was 404
Apr 19 15:17:11 onedev1-idm-blue-6d67495479-cv8jm onedev1-idm-blue !!!! confd failed to process templates !!!!
```

I do not want to attach the full MIC log because I am not entirely familiar with what gets logged in it and I do not want to post anything about our application/azure subscription/managed identities etc.   Is there something specific you would like me to look for in the logs?

I should add that SOME pods end up acquiring a token but it takes dozens of retries which takes a long time and can cause our application healthchecks and readiness probes to timeout waiting


AzureIdentity and AzureIdentityBinding yamls below.  Again, these have not changed.

```apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{CLUSTER_NAME}}-podidentity-binding
spec:
  azureIdentity: {{CLUSTER_NAME}}-podidentity
  selector: managed_identities


apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{CLUSTER_NAME}}-podidentity
spec:
  type: 0
  resourceID: {{CLUSTER_IDENTITY_RESOURCE_ID}}
  clientID: {{CLUSTER_IDENTITY_CLIENT_ID}}
```

**Comment by aramase** [comment]
> I do not want to attach the full MIC log because I am not entirely familiar with what gets logged in it and I do not want to post anything about our application/azure subscription/managed identities etc. Is there something specific you would like me to look for in the logs?

Check the MIC logs for the pod that's failing to acquire the token. NMI logs will only show failed to get token but MIC is the one that needs to assign the identity for the pod. If there are no logs for the pod in MIC, then it could be misconfigured labels. Also, there is a metric for how long the cloud PUT operation takes for assigning identity which can be useful to see why pods aren't able to get a token.

Also, from which version did you upgrade to `v1.8.8`. Did you review the [breaking changes](https://azure.github.io/aad-pod-identity/docs/#breaking-changes) between minor version upgrades?

**Comment by ryanbradley7** [comment]
I found a solution that fixed the issue for us and I am hoping it helps others.  Workload Identity is in preview still and should not be recommended as a solution yet, especially since AAD Pod Identity is still being used by many people and hasn't been deprecated. 

The solution that worked for us was to use AAD Pod Identity in "managed mode".  Please refer to [https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/ ](url)

Two things to note is that the identity and identity bindings are namespaced and must be created in the same namespace as the pods that will use them and the managed identities in Azure must be manually assigned as a system assigned identity to the VMSS (since MIC is no longer doing that dynamically)

The issue is with how MIC binds the identities to the nodes.  Every time a pod with a new identity is created, it must associate that managed identity to the VMSS (in the MC_* resource group). It turns out that it was taking a very long time for MIC to assign the identity to the VMSS which caused our pods to fail to obtain an auth token and our pods would fail. Using AAD Pod Identity in managed mode removes this step and makes obtaining an auth token almost instantaneous.

This only became an issue in the last couple of weeks which leads me to believe that there were some changes to request limits/throttling or how VMSS get assigned an identity on Azure's end. It would be great if we could get an answer on this

**Comment by ondrejhlavacek** [comment]
@aramase 

> To avoid such identity assignment delays, you can run AAD Pod Identity in managed mode: https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/. In this mode, there is only NMI. The identities are manually assigned and hence there is no assignment/unassignment delay. Workloads will have access to the identity right when they're deployed and running.

Thanks, we will look into this.

**Comment by ondrejhlavacek** [comment]
An update from my end, we were able to partly work around the issue. The root cause was that we had a garbage collector deleting old pods. We have a huge number of short lived pods (hundreds per hour) and we need to clean up pod definitions regularly to avoid Kubernetes API issues. This happened once per hour in batch and once deleted the identity unassignment took place. We have changed the interval from once per hour to once every 10 minutes which decreases the number of identities/pods for deassignment.

**Comment by ondrejhlavacek** [comment]
Anyway, we're back at square one. He have a lot of microbatch workloads on the cluster (thousands of pods created/deleted each hour) and with rising traffic all our workarounds start to gradually fail. 

We're in a situation where a mic assignment loop can take up to 30 minutes which blocks identity assignment. 

The MIC log is full of these messages

```
request.go:665] Waited for 3.983844657s due to client-side throttling, not priority and fairness, request: 
  PUT:https://10.1.0.1:443/apis/aadpodidentity.k8s.io/v1/namespaces/default/azureassignedidentities/job-22346885-job-queue-jobs-com-keboola-azure-north-europe-job-queue-identity
```

The client-side throttling is the root cause of the long MIC loop. Is there a way to tune the MIC Kubernetes client parameters to avoid throttling?

First few API calls are quick but the throttling comes in very quickly. Note that in a batch we often have to do more than 100 patches. 

![image](https://user-images.githubusercontent.com/497675/183841433-3cbd9953-1f28-4d9d-b2ed-3c1440305005.png)

Anyway, I am quite hesitant to believe switching to managed mode will help. Can anyone shed some light here please if it will actually help? Thanks!

**Comment by aramase** [comment]
> Anyway, I am quite hesitant to believe switching to managed mode will help. Can anyone shed some light here please if it will actually help? Thanks!

@ondrejhlavacek Switching to managed mode will help because there is no `AzureAssignedIdentity` in that mode. There are no API calls to PATCH crds or cloud provider API calls as there is no MIC.

**Comment by ondrejhlavacek** [comment]
That's actually good news. Thanks, we'll give it a try!

**Comment by ondrejhlavacek** [comment]
Back here with another question, I have implemented `az vmss identity assign` (and `az vmss update-instances`) for all identities and node pools we have and in the last 24 hours one of the node pools lost twice all the assignments (except for the default MC RG). 

I am trying to debug this issue and it seems, that there is no log of identity assignment/unassignment in the VMSS activity log. Is there a way to monitor these events so I can figure out when the identity was unassigned relate that to other events in the app/infrastructure?

I have observed these events
- multiple node pool scaleup/scaledown events, possibly also down to 0 (but this happened to other node pools as well)
- accidentally triggered MIC deployment (but the NMI is still in managed mode)

But none of the other node pools and assignments (even of the same user managed identity) seemed to be affected, only one, twice within last 24 hours.
