### ISSUE TITLE
MIC Restarts continuously

### ISSUE THREAD

**Issue by rajdhandus** [Azure/aad-pod-identity#1278]
**Have you**

- [x ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

MIC Restart Continuously as it hit the memory limits. 

**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**
4.1.0 helm release

**Kubernetes version**
1.22.2

**Additional context**
![image](https://user-images.githubusercontent.com/6888014/167210801-406e6068-e3c7-429e-868b-0f842e575e56.png)

**Comment by aramase** [comment]
Helm chart release `4.1.0` is using pod identity release `v1.8.0`. This is an old release (1yr old) and there have been multiple fixes in the releases after. Could you upgrade to the latest and see if the issue is resolved?

If you see issues with latest release, please also provide the logs from the restarted MIC pod (using the `-p` flag).
