### ISSUE TITLE
Incorrectly appending create list to the delete list

### ISSUE THREAD

**Issue by Pothulapati** [Azure/aad-pod-identity#141]
Hey,

In the `SplitAzureAssignedIDs` method, if the condition is `in(old) && !in(new)`  then we have delete. So, We should be appending the id to the `delete` list but it is incorrectly being appended to the `create` list as shown here.
https://github.com/Azure/aad-pod-identity/blob/2540a613757050f326755062e6d5a3682d9f8371/pkg/mic/mic.go#L388

If we see the other condition, i.e `!in(old) && in(new)`, then we have to create the id. So we are appending them rightly to the `create`  list as shown here.
https://github.com/Azure/aad-pod-identity/blob/2540a613757050f326755062e6d5a3682d9f8371/pkg/mic/mic.go#L365

Did I understand something wrong?

**Comment by kkmsft** [comment]
Thank you @Pothulapati. 

The issue manifests when there are delete and add in the same cycle. Because we are running delete cycles first and then performing create cycles, the effect of create list adding itself to delete gets nullified there because create eventually gets done, right after the delete. Nevertheless this causes an unnecessary deletion and addition to the underlying vm identity. As for deletions take effect one at a time because only one 'real' to-be-deleted one gets appended in one cycle. Eventually the others also get deleted in subsequent cycles.

Working on the fix and test to repro any side effects of this.

**Comment by kkmsft** [comment]
Fix merged. Closing the bug.
