### ISSUE TITLE
Make aad-pod-identity more generic (to work with non-aks clusters)

### ISSUE THREAD

**Issue by philwinder** [Azure/aad-pod-identity#185]
Hi there,
I'm running a number of self-manged Kubernetes clusters on Azure. It has taken me a long time to get this project working. There's been a scattering of issues, but one general problem was that everything is catered towards AKS (documentation, examples, etc.). 

Here is a list of some of my issues:
- We need a proper, stable, helm chart that is not specific to aks (it should work with any k8s cluster on azure) (#122). I've seen a few issues related to this.
- The `azure.json` cloud credentials are not usually located at `/etc/kubernetes/azure.json` on non-aks clusters (https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml#L201)
Instead, I created a secret that contained this information and mounted that secret as a file.
- Related to this, we shouldn't mount any secrets file anyway, because it increases the possibility of those credentials being leaked. They should not even be on the nodes in aks IMO.
- The example helm chart in this repository incorrectly attempts to use a static kubeconfig and certs. This is not required when using RBAC. (https://github.com/Azure/aad-pod-identity/blob/master/charts/aad-pod-identity/templates/infra.yaml#L158)
- You don't need to set the "Managed Identity Operator" role if the service principal you are using already has permission on your resource group (https://github.com/Azure/aad-pod-identity#providing-required-permissions-for-mic)
- Creating user identities and roles is only required _when_ you want to give something a role. It is not required for installation. (https://github.com/Azure/aad-pod-identity#create-user-azure-identity)
- The demo is too complicated. The simple demo I'm using is to spin up the azure-cli container and do a `az login --identity`. This works to show that it can get credentials.
- Need a second more realistic demo using a custom role. E.g. managed DB access?
- Need a third demo showing how to make this as secure as possible, with namespacing enabled and RBAC on the AzureIdentity to prevent overzealous Engineers from hacking around the limits I place on them :-)
- Improvements to the README, to move the installation and use into separate sections.
- I had one instance where I accidentally had an MSI attached to a node that didn't exist. I was getting lots of errors on the `CreateOrUpdate` method. I got confused because I didn't know where this mysterious MSI was coming from; I thought it was a misused client_id or something. This is probably azure's fault (I've had a range of issues with their cli and API), but worth noting here.
- I had issues with my iptables configuration. Because this is running in host mode, pods need access to the host IPs. Quite often this is firewalled for security reasons. E.g. you don't want pods arbitrarily telnetting port 22 on the host. This was the exception I had to add: `sudo iptables -t filter -A IN_drop_allow -p tcp --dport 2579 -m conntrack --ctstate NEW -j ACCEPT`. It may be different for other people due to the way we have hardened the host.

Overall, this is a great project, which prevents the need of putting lots of service principals in secrets for all our developers. I would like to see the project to emulate KIAM (https://github.com/uswitch/kiam). I've had a lot of success with this, mainly due to the fact that it's more generic and has a helm chart.

Thanks!

**Comment by kkmsft** [comment]
@philwinder - Thank you for detailed suggestions. Definitely very useful suggestions. We will use this when prioritizing some of the future work.

Would you be interested in doing a PR for simpler demo you mentioned ?

**Comment by thanasisk** [comment]
:+1: for this issue - I would really like to use this in non-AKS Azure clusters

**Comment by aramase** [comment]
@thanasisk Would love to understand what are the blockers now for using with non-aks cluster? 

`/etc/kubernetes/azure.json` is mounted so aad-pod-identity components can use the cluster service principal (SP) to make azure cloud api calls. But with the latest release we have added a feature to allow using a separate SP for pod-identity components. This can be configured using a secret - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.noazure-json.md. We have added also added this option as part of helm charts.

**Comment by thanasisk** [comment]
thanks for the clarification. The mistake was on my side but it might be worth noting for software resiliency reason from your side as well. If ProviderID is not set AND using VMSS, it falls back to using the DNS node name (bug 1). If the ProviderID is set manually but the proper permissions are NOT setup in AD, the pods start getting segfaults (bug 2).

**Comment by chewong** [comment]
I think we have addressed all of your concerns in our latest releases. Feel free to open a new issue if you are experiencing any new issues.

| Issue | Fix |
|-|-|
| We need a proper, stable, helm chart that is not specific to aks (it should work with any k8s cluster on azure) (#122). I've seen a few issues related to this. | Our helm chart should now be flexible enough to be deployed to any Kubernetes clusters on Azure. See https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity#configuration on different config you could set. More specifically, you can see https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity#installing-charts on how to install aad-pod-identity without `/etc/kubernetes/azure.json` |
|The azure.json cloud credentials are not usually located at /etc/kubernetes/azure.json on non-aks clusters (https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml#L201). Instead, I created a secret that contained this information and mounted that secret as a file.  | See https://github.com/Azure/aad-pod-identity/issues/185#issuecomment-531304552 and the comment above. |
|Related to this, we shouldn't mount any secrets file anyway, because it increases the possibility of those credentials being leaked. They should not even be on the nodes in aks IMO. | If you are concerned that your credentials will get leaked, you should consider using [AKS Managed Identity](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity). We would still need to mount `/etc/kubernetes/azure.json` but it won't contain sensitive information. |
|The example helm chart in this repository incorrectly attempts to use a static kubeconfig and certs. This is not required when using RBAC. (https://github.com/Azure/aad-pod-identity/blob/master/charts/aad-pod-identity/templates/infra.yaml#L158) | I believe the relevant code has been removed. |
|You don't need to set the "Managed Identity Operator" role if the service principal you are using already has permission on your resource group (https://github.com/Azure/aad-pod-identity#providing-required-permissions-for-mic) | That's correct. |
|Creating user identities and roles is only required when you want to give something a role. It is not required for installation. (https://github.com/Azure/aad-pod-identity#create-user-azure-identity) | That's correct. |
|The demo is too complicated. The simple demo I'm using is to spin up the azure-cli container and do a az login --identity. This works to show that it can get credentials. | We have a new demo, which is much simpler and you can try it by only copying and pasting necessary code to your terminal - https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough/.|
|Need a second more realistic demo using a custom role. E.g. managed DB access? | Please see https://github.com/Azure/aad-pod-identity/issues/153. |
|Need a third demo showing how to make this as secure as possible, with namespacing enabled and RBAC on the AzureIdentity to prevent overzealous Engineers from hacking around the limits I place on them :-) | Please see https://azure.github.io/aad-pod-identity/docs/best-practices/. |
|Improvements to the README, to move the installation and use into separate sections. | Please see https://azure.github.io/aad-pod-identity/. |
|I had one instance where I accidentally had an MSI attached to a node that didn't exist. I was getting lots of errors on the CreateOrUpdate method. I got confused because I didn't know where this mysterious MSI was coming from; I thought it was a misused client_id or something. This is probably azure's fault (I've had a range of issues with their cli and API), but worth noting here. | If you use the latest version, MIC should be able to omit erroneous MSI before retrying the same identity assignment request. |
|I had issues with my iptables configuration. Because this is running in host mode, pods need access to the host IPs. Quite often this is firewalled for security reasons. E.g. you don't want pods arbitrarily telnetting port 22 on the host. This was the exception I had to add: sudo iptables -t filter -A IN_drop_allow -p tcp --dport 2579 -m conntrack --ctstate NEW -j ACCEPT. It may be different for other people due to the way we have hardened the host. | aad-pod-identity now binds to localhost instead of hostIP. |
