### ISSUE TITLE
User Assigned Identity Not Removed from VM

### ISSUE THREAD

**Issue by droessmj** [Azure/aad-pod-identity#217]
Using AKS, Kubernetes version: 1.12.6

AAD Pod Identity Info:
- NMI: v1.4
- MIC: v1.3

##Symptoms
- Pods were stuck on a crashloopbackoff due to inability to authN to database using User Assigned Identity. MIC logs indicated that the correct binding was being applied to the pods in question, however the AzureIdentity resource referenced in MIC logs did not match the resources existing in Kubernetes. The AzureIdentity resource had been updated to consume a separate, newer User Assigned Identity resource in Azure. Logs indicated that the prior User Assigned Identity was attempting to be bound, but a 403 was being returned (as the prior identity resource was deleted from its resource group). 

##Error Message - Amended to remove identifying info
```
Event(v1.ObjectReference{Kind:"AzureIdentityBinding", Namespace:"default", Name:"MSI-BINDING-PLACEHOLDER", UID:"b4b93419-78ae-11e9-8dbb-e6d966016eaf", APIVersion:"aadpodidentity.k8s.io/v1", ResourceVersion:"5608855", FieldPath:""}): type: 'Warning' reason: 'binding apply error' Applying binding MSI-BINDING-PLACEHOLDER node aks-agentpool-ID-0 for pod APP-batch-7d96f9c87f-lgf97-default-msi-APP-mybatch1-d
resulted in error compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'GUID' with object id 'GUID' has permission to perform action 'Microsoft.Compute/virtualMachines/write' on scope '/subscriptions/SUBSCRIPTION/virtualMachines/aks-agentpool-ID-0'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/SUBSCRIPTION8/resourcegroups/RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/IDENTITY-Name'."
```

##Recorded steps performed to recreate and resolve
- New MSI was created and AKS Cluster SP was assigned Managed Identity Operator RBAC role for MSI
- New AzureIdentity and AzureIdentityBinding was created. Deployment was updated to consume new binding
- Pods failed to authN to an Azure SQL database. MIC logs showed references to old User Assigned Identity
- Killing NMI and MIC, along with multiple pods themselves did not resolve .
- Deploying new AzureIdentity and AzureIdentityBinding repeatedly did not resolve.
- Scaling cluster down from 3 nodes to 1 node did not resolve the issue. We did not scale back up after the downscale until after issue was resolved, however expectations are that the upscale may have resulted in working AAD Pod Identity on the two new VM nodes 
- Manually deprovisioning the user assigned identity from the VM resolved the issue. Once the User Assigned Identity was removed, the new identity was applied instantly and application pods began running as expected. Scaling events post-removal had no problem.

**Comment by droessmj** [comment]
@dstrebel - Opened this in this project rather than AKS as it seems more coupled to Pod Identity than general AKS, but there may be overlaps.

**Comment by kkmsft** [comment]
@droessmj - sorry for delay in updating. The behavior seen of the identity not going away is not expected. We will investigate to figure out what is going on. Meanwhile, wanted to confirm - Is this something which you hitting often ? After the manual removal, is everything alright and assignment and are fine in the subsequent operations ?

**Comment by aramase** [comment]
@kkmsft I hit this issue while running some e2e tests yesterday. I think the issue is we delete the assigned identity and then remove the msi from the node. However if there is an error while removing msi, we don't retry. 

https://github.com/Azure/aad-pod-identity/blob/c4fb5db010fe0748f16b3607d8952f15cec9caea/pkg/mic/mic.go#L231-L237

I think if we see a failure here, we should put back the assigned identity so we can retry the msi removal in the next sync cycle.

**Comment by kkmsft** [comment]
Thank you - @aramase - can you look into why this error would happen in conjunction with this issue so that we can fit in all the pieces here: 

"Event(v1.ObjectReference{Kind:"AzureIdentityBinding", Namespace:"default", Name:"MSI-BINDING-PLACEHOLDER", UID:"b4b93419-78ae-11e9-8dbb-e6d966016eaf", APIVersion:"aadpodidentity.k8s.io/v1", ResourceVersion:"5608855", FieldPath:""}): type: 'Warning' reason: 'binding apply error' Applying binding MSI-BINDING-PLACEHOLDER node aks-agentpool-ID-0 for pod APP-batch-7d96f9c87f-lgf97-default-msi-APP-mybatch1-d
resulted in error compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'GUID' with object id 'GUID' has permission to perform action 'Microsoft.Compute/virtualMachines/write' on scope '/subscriptions/SUBSCRIPTION/virtualMachines/aks-agentpool-ID-0'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/SUBSCRIPTION8/resourcegroups/RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/IDENTITY-Name'."

**Comment by kkmsft** [comment]
Btw, @aramase  - that fix of assignment back makes sense. But thinking more - we need to maintain the state of those underlying assignment in the assignedidentity instead of removing and adding for better tracing. This can be used in other scenarios as well where we have underlying assignment failure as well.

**Comment by aramase** [comment]
@kkmsft is it possible the role assignment was changed after the add was done? Is this logs from @droessmj cluster? I can't recreate it consistently. Happened to me only once.

**Comment by aramase** [comment]
> Btw, @aramase - that fix of assignment back makes sense. But thinking more - we need to maintain the state of those underlying assignment in the assignedidentity instead of removing and adding for better tracing. This can be used in other scenarios as well where we have underlying assignment failure as well.

Totally makes sense. So what you're suggesting is we add events to the assigned identity on failure and remove the assigned identity only when we successfully remove the msi from the node right?

**Comment by droessmj** [comment]
> @droessmj - Apologies for delay in updating. The behavior seen of the identity not going away is not expected. We will investigate to figure out what is going on. Meanwhile, wanted to confirm - Is this something which you hitting often ? After the manual removal, is everything alright and assignment and are fine in the subsequent operations ?

After manual removal the issue didn't recur and nothing further was required. The real issue was in discovering the underlying "sticky" MSI, as the K8s cluster showed no presence of the original other than the MIC log entries.

**Comment by kkmsft** [comment]
With #219 , states are introduced for assigned identities. With this, when an error occurs, we will keep retrying based on the state in the next cycle.

**Comment by midhun-mohan** [comment]
@kkmsft  @aramase I have reached to the same state as of this issue. 
Do you have any pointers how can we fix this ?

Below is the error from MIC  (Just removed the exact app name and agent name)
I0131 10:22:12.798563       1 mic.go:856] Updating msis on node aks-agentpool-********-2 failed, but identity app-azure-id-binding has successfully been removed from node
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1126482]

**Comment by aramase** [comment]
@midhun-mohan which version of pod-identity are you using?

**Comment by midhun-mohan** [comment]
@aramase we are running on 1.5.3.
mic:1.5.3
nmi:1.5.3
