### ISSUE TITLE
mic failed to start after upgrading to latest version

### ISSUE THREAD

**Issue by omerlh** [Azure/aad-pod-identity#369]
**Describe the bug**
Mic failed to start with the following error:
```
E0902 06:03:31.552100       1 cloudprovider.go:69] Get cloud env error: autorest/azure: There is no cloud environment matching the name ""
F0902 06:03:31.552323       1 main.go:69] Could not get the MIC client: autorest/azure: There is no cloud environment matching the name ""
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc000470100, 0xc000474000, 0x8b, 0xc2)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:769 +0xd4
github.com/golang/glog.(*loggingT).output(0x2087e00, 0xc000000003, 0xc00014ba20, 0x2007a2e, 0x7, 0x45, 0x0)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:720 +0x329
github.com/golang/glog.(*loggingT).printf(0x2087e00, 0x3, 0x142afd2, 0x21, 0xc000567f28, 0x1, 0x1)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:655 +0x14b
github.com/golang/glog.Fatalf(0x142afd2, 0x21, 0xc000567f28, 0x1, 0x1)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:1148 +0x67
main.main()
	/go/src/github.com/Azure/aad-pod-identity/cmd/mic/main.go:69 +0x699
```

**Steps To Reproduce**
Upgrade existing MIC to the latest version

**Expected behavior**
MIC started correctly

**AAD Pod Identity version**
1.5.2
**Kubernetes version**
1.12.7
**Additional context**
I guess when upgrading I missed something. All I did was updating the version in our yamls to the latest version - guess there is a new config param that I missed. Is there an official upgrade guide? Also, are there plans to create a "pure" chart? E.g. a chart that installs mic and NMI? Look like the current chart does more than that...

**Comment by aramase** [comment]
@omerlh There are quite a few changes in the deployment manifest for `v1.5.2` compared to `mic:1.3/nmi:1.4`. PTAL at latest deployment manifest -https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml to apply the new release. 

The initial plan was to move the charts to official helm repo. But since aad-pod-identity works only with azure cluster, that doesn't seem to be a good location to have the charts. I'll be moving the new charts to the charts dir here soon and then it should be good to go.

**Comment by aramase** [comment]
Closing with https://github.com/Azure/aad-pod-identity/pull/373
