### ISSUE TITLE
Service Principal identities should work outside Azure

### ISSUE THREAD

**Issue by desek** [Azure/aad-pod-identity#380]
**Describe the request**
During local development with minikube (or other local k8s) I'd like to be able to use Service Principal identities (type=1) to be available via aad-pod-identity when using it together with "adminSecret" parameters during deploy rather than MSI.
If aad-pod-identity uses a Service Principal via the adminSecret parameter to interact with Azure together with an AzureIdentity resource that's a Service Principal it should be possible to use it during local development.

**Explain why AAD Pod Identity needs it**
Make local development environment closer to non-local environments.

**Describe the solution you'd like**
To be able to get tokens using ADAL for the Service Principal definined in the AzureIdentity resources which is available via AzureIdentityBinding resource.

**Describe alternatives you've considered**
Using application-level controls and functions to make ADAL get tokens for Service Principal based on environment variables.

**Additional context**

**Comment by droessmj** [comment]
Specifically for local development, would this approach be the recommended means to work with aad pod identity on a local cluster? Or, do other ways exist to better emulate? I ask as our org is continuing to mature in its use of Kubernetes and pod identity, and I'd love to get developers used to deploying and testing full solutions on a local cluster rather than testing only component containers locally.

**Comment by bdschaap** [comment]
My use case is a little different for this feature request and I wanted to make note of it.  I use AKS for my Azure K8s clusters but [RKE](https://rancher.com/docs/rke/latest/en/) for my on-prem K8s clusters.  I would like to use Service Principal identities through AAD Pod Identity to connect to Azure resources for both types of my K8s clusters.

Has a timeline been set for when this Service Principal identities will work outside of Azure?

**Comment by aramase** [comment]
@bdschaap You can deploy pod identity in managed mode and configure service principal identities for use outside of Azure. Here are the docs for managed mode: https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/

Examples in here for `AzureIdentity`, `AzureIdentityBinding` and Kubernetes secret required for service principal: https://azure.github.io/aad-pod-identity/docs/concepts/azureidentity/
https://azure.github.io/aad-pod-identity/docs/concepts/azureidentitybinding/

**Comment by bdschaap** [comment]
Thanks I'll give it a try.  I previously saw that doc but was probably confused by the az vm and az vmss commands that are for Azure CLI since my RKE use case is for on-prem K8s clusters.

Last week I encountered the issue where it was checking for kubenet in that scenario even with the switch to disable it.  However, I saw that you fixed that in 1.7.5 and just released it.  Will try again.

**Comment by bdschaap** [comment]
I confirmed that managed mode works outside of Azure as you mentioned earlier.  Thanks!

**Comment by aramase** [comment]
As mentioned in the [announcement](https://cloudblogs.microsoft.com/opensource/2022/01/18/announcing-azure-active-directory-azure-ad-workload-identity-for-kubernetes/), we are planning to replace AAD Pod Identity with [Azure Workload Identity](https://azure.github.io/azure-workload-identity). Going forward, we will no longer add new features to this project in favor of Azure Workload Identity. However, we will continue patching critical bugs and security vulnerabilities until further notice.

Azure Workload Identity will work on Kubernetes clusters hosted in any cloud or on-premises.
