### ISSUE TITLE
Add support for pods running through virtual kublet.

### ISSUE THREAD

**Issue by iyyappam** [Azure/aad-pod-identity#470]
For pods running on AKS cluster with virtual kublet (backed by ACI), the AAD pod identity doesn't work. Since in the current architecture NMI agent runs as daemon set on each node, but on virtual nodes there are no nodes to run the NMI agent to intercept the call. Removing the constraint on running NMI as daemon set could solve the issue.

**Comment by kkmsft** [comment]
Virtual Kubelet can use aad-pod-identity (to get userMSI tokens) to contact ACI, instead of using Service Principal. But aad-pod-identity cannot be used for pods running within the ACI since MIC/NMI cannot be run on the underlying VM within the ACI service. This is outside the scope of what we intend with aad-pod-identity project. Hence closing this issue.
