### ISSUE TITLE
Repeat failures to get pod name lead to returning 500

### ISSUE THREAD

**Issue by ianjirka** [Azure/aad-pod-identity#473]
aad-pod-identity 1.5.4
Kubernetes (AKS) 1.14.6

Seems related to #99, except retry is not sufficient to correct it.

We see this a lot on one of our clusters right now - it's definitely not transient. 

ERROR: logging before flag.Parse: E0110 00:15:24.965945       1 client.go:161] pod list empty
time="2020-01-10T00:15:24Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 1"
ERROR: logging before flag.Parse: E0110 00:15:25.266168       1 client.go:161] pod list empty
time="2020-01-10T00:15:25Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 2"
ERROR: logging before flag.Parse: E0110 00:15:25.566422       1 client.go:161] pod list empty
time="2020-01-10T00:15:25Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 3"
ERROR: logging before flag.Parse: E0110 00:15:25.866620       1 client.go:161] pod list empty
time="2020-01-10T00:15:25Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 4"
ERROR: logging before flag.Parse: E0110 00:15:26.166997       1 client.go:161] pod list empty
time="2020-01-10T00:15:26Z" level=error msg="missing podname for podip:10.244.4.185, pod list empty" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.4.185
time="2020-01-10T00:15:26Z" level=info msg="Status (500) took 1201244812 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.4.185

How can I troubleshoot further?

**Comment by kkmsft** [comment]
@ianjirka  - Thank you for using aad-pod-identity.
Are there other logs in NMI indicating connection or watch failure with the API Server ?

**Comment by ianjirka** [comment]
Thanks @kkmsft - nothing jumps out to me.  It seems it hit a condition and I see mostly failure after this point in time.

time="2020-01-08T00:22:15Z" level=info msg="Status (200) took 4251104 ns" req.method=GET req.path=/metadata/instance req.remote=10.244.4.130
time="2020-01-08T00:23:17Z" level=info msg="Status (200) took 3496603 ns" req.method=GET req.path=/metadata/instance req.remote=10.244.4.101
time="2020-01-08T00:29:17Z" level=info msg="Status (200) took 3684003 ns" req.method=GET req.path=/metadata/instance req.remote=10.244.4.129
time="2020-01-08T00:36:17Z" level=info msg="Status (200) took 5584605 ns" req.method=GET req.path=/metadata/instance req.remote=10.244.4.101
time="2020-01-08T00:37:17Z" level=info msg="Status (200) took 3091802 ns" req.method=GET req.path=/metadata/instance req.remote=10.244.4.130
time="2020-01-08T00:41:17Z" level=info msg="Status (200) took 3357703 ns" req.method=GET req.path=/metadata/instance req.remote=10.244.4.129
time="2020-01-08T00:48:17Z" level=info msg="Status (200) took 3780705 ns" req.method=GET req.path=/metadata/instance req.remote=10.244.4.101
time="2020-01-08T00:49:15Z" level=info msg="Status (200) took 3658704 ns" req.method=GET req.path=/metadata/instance req.remote=10.244.4.130
time="2020-01-08T00:52:17Z" level=info msg="Status (200) took 4262004 ns" req.method=GET req.path=/metadata/instance req.remote=10.244.4.129
ERROR: logging before flag.Parse: E0108 00:59:45.197680       1 client.go:161] pod list empty
time="2020-01-08T00:59:45Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 1"
ERROR: logging before flag.Parse: E0108 00:59:45.506409       1 client.go:161] pod list empty
time="2020-01-08T00:59:45Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 2"
ERROR: logging before flag.Parse: E0108 00:59:45.806644       1 client.go:161] pod list empty
time="2020-01-08T00:59:45Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 3"
ERROR: logging before flag.Parse: E0108 00:59:46.107046       1 client.go:161] pod list empty
time="2020-01-08T00:59:46Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 4"
ERROR: logging before flag.Parse: E0108 00:59:46.454433       1 client.go:161] pod list empty

I'll follow up with you internally with the full log

**Comment by ianjirka** [comment]
Circling back - killing nmi mitigated the issue for us.

**Comment by kkmsft** [comment]
Thanks @ianjirka . Closing this issue as the issue got mitigated. If this issue happens again let's attempt at a profile snapshot and see what is going on with the nmi process.

**Comment by kwaazaar** [comment]
Should be reopened.

I try to use a managed identity for a job that runs every minute. Sometimes it works, sometimes it doesn't. This is the logs from NMI that shows both success and failures:

time="2020-02-05T10:57:34Z" level=info msg="matched identityType:0 clientid:88eb##### REDACTED #####1423 resource:https://vault.azure.net/" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.20.105
**time="2020-02-05T10:57:34Z" level=info msg="Status (200) took 5707153 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.20.105**
E0205 10:58:21.526080       1 client.go:168] pod list empty
time="2020-02-05T10:58:21Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 1"
E0205 10:58:21.831909       1 client.go:168] pod list empty
time="2020-02-05T10:58:21Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 2"
E0205 10:58:22.132125       1 client.go:168] pod list empty
time="2020-02-05T10:58:22Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 3"
E0205 10:58:22.432408       1 client.go:168] pod list empty
time="2020-02-05T10:58:22Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 4"
E0205 10:58:22.732700       1 client.go:168] pod list empty
time="2020-02-05T10:58:22Z" level=error msg="missing podname for podip:10.234.20.72, pod list empty" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.20.72
**time="2020-02-05T10:58:22Z" level=info msg="Status (500) took 1206767900 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.20.72**
E0205 10:58:24.735648       1 client.go:168] pod list empty
time="2020-02-05T10:58:24Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 1"
E0205 10:58:25.036053       1 client.go:168] pod list empty
time="2020-02-05T10:58:25Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 2"
E0205 10:58:25.336395       1 client.go:168] pod list empty
time="2020-02-05T10:58:25Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 3"
E0205 10:58:25.636796       1 client.go:168] pod list empty
time="2020-02-05T10:58:25Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 4"
E0205 10:58:25.937040       1 client.go:168] pod list empty
time="2020-02-05T10:58:25Z" level=error msg="missing podname for podip:10.234.20.72, pod list empty" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.20.72
time="2020-02-05T10:58:25Z" level=info msg="Status (500) took 1201505679 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.20.72
E0205 10:58:31.941893       1 client.go:168] pod list empty
time="2020-02-05T10:58:31Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 1"
E0205 10:58:32.242130       1 client.go:168] pod list empty
time="2020-02-05T10:58:32Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 2"
E0205 10:58:32.542330       1 client.go:168] pod list empty
time="2020-02-05T10:58:32Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 3"
E0205 10:58:32.842541       1 client.go:168] pod list empty
time="2020-02-05T10:58:32Z" level=warning msg="List pod error: pod list empty. Retrying, attempt number: 4"
E0205 10:58:33.142823       1 client.go:168] pod list empty
time="2020-02-05T10:58:33Z" level=error msg="missing podname for podip:10.234.20.72, pod list empty" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.20.72
time="2020-02-05T10:58:33Z" level=info msg="Status (500) took 1201028805 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.20.72
**time="2020-02-05T10:58:47Z" level=info msg="matched identityType:0 clientid:88eb##### REDACTED #####1423 resource:https://vault.azure.net/" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.20.72
time="2020-02-05T10:58:47Z" level=info msg="Status (200) took 4418839 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.20.72**

When I check the IP myself, it turns out it's the IP of the pod of the job. Eg:
kubectl get po --all-namespaces -o wide | grep 10.234.20.41
