### ISSUE TITLE
MIC tried to assign the incorrect managed identity which is different from the AzureIdentity 

### ISSUE THREAD

**Issue by Shuanglu** [Azure/aad-pod-identity#487]
**Describe the bug**
User created an identity under RG '**PECAzureInfraAKS01**'.
Due to some reason, user recreated managed identity in another RG '**PECAzureInfraAKS01-nodes**' with the same name. After this, AzureIdentity and AzureIdentityBinding were recreated. 
Application pod was assigned to the VM and MIC started to assign the identity but failed due to error below.

E0122 03:51:56.411776       1 vmss.go:57] compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'xxx' with object id 'xxx' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/xxx/resourceGroups**/PECAzureInfraAKS01-nodes**/providers/Microsoft.Compute/virtualMachineScaleSets/aks-xxx-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/xxx/resourcegroups/**PECAzureInfraAKS01**/providers/Microsoft.ManagedIdentity/userAssignedIdentities/AppGwIdentity' or the linked scope(s) are invalid."

**Steps To Reproduce**
Describe as above
**Expected behavior**
MIC assign correct resource
**AAD Pod Identity version**
MIC version 1.5.3(installed by helm)
**Kubernetes version**
1.15.7
**Additional context**

**Comment by jamihuq** [comment]
1.	When you delete an identity from the portal the identity is still connected to the nodes
2.	If the identity and namespace are deleted MIC will use the identity that is still on the nodes. 
3.	Since you removed the whole namespace, the Azure Identity and binding was deleted. So MIC was unable to get the client id and old identity from the the VMSS. When the new identity was requested to be assigned we got the existing list from vmss which had the old identity and appended the new identity to it.
4.	The vm update with identities failed because azure didn't recognize one of the ids in the list anymore 
5.	Please run “az vmss identity show –resource-group <newRG> --name <VMSS>” and you will see the old RG still being referenced in your userAssignedIdentities

Mitigation:
You will need to remove the old identity from the node and MIC will use the new identity. Please run az vmss identity remove as per https://docs.microsoft.com/en-us/cli/azure/vmss/identity?view=azure-cli-latest
1.	az vmss identity remove –resource-group <newRG> --name <VMSSName> --identities “/subscriptions/<subID>/resourceGroups/<oldRG>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IdentityName>”

**Comment by aramase** [comment]
this issue will be resolved with https://github.com/Azure/aad-pod-identity/pull/522
