### ISSUE TITLE
Why default namespace

### ISSUE THREAD

**Issue by lgmorand** [Azure/aad-pod-identity#549]
Is there a specific reason that NMI and MIC are deployed in default namespace ?

Documentation says that default ns should not be used in  production and other tooling (flexvolume, kured, etc) all create their own namespace. why don't we have a "pod-identity" or something else to deploy NMI and MIC ?

**Comment by aramase** [comment]
@lgmorand The first time deployment manifests were added, the pods were deployed in default namespace. The reason we haven't changed the namespace in the manifests is because most of the user rely on the [raw deployment url](https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml) for deployment/upgrade. If the namespace is changed in the deployment now, it'll be a breaking change for existing users. 

However you can deploy the pod-identity in any namespace using the helm chart.

**Comment by lgmorand** [comment]
Ok thanks I agree for breaking change but sometimes better be a breaking change than a long-term bad practice :)

But I'm fine with your vision. thanks
