### ISSUE TITLE
Included demo isn't working 

### ISSUE THREAD

**Issue by gearama** [Azure/aad-pod-identity#552]
**Describe the bug**
included demo fails constantly with 403 and 404 http errors in the mic and nmi pods 
also the cluster created through the demo scripts seems to be missing the --enable-managed-identity flag in the create command

**Steps To Reproduce**
follow the demo instructions at https://github.com/Azure/aad-pod-identity/blob/master/README.md 

**Expected behavior**
to be able to run the demo 

**AAD Pod Identity version**

**Kubernetes version**
default on azure , latest available
**Additional context**

**Comment by tezzigator** [comment]
Its not working for me either, using AKS managed kubernetes 1.16.7, here are my details:
AKS cluster was built using MSI instead of a SP for building components in the special resource group.
The user managed identity I created is in that same special resource group, so I didnt do step #6 (Set Permissions for MIC)
NMI doesnt really show any errors.
MIC has error:
`E0410 02:22:57.185044       1 mic.go:848] Applying binding mybinding node aks-default-0REDACTED0-0 for pod mypod resulted in error compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="AuthorizationFailed" Message="The client 'REDACTED-UUID' with object id 'REDACTED-UUID' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/write' over scope '/subscriptions/REDACTED-subscription/resourceGroups/myresourcegroup/providers/Microsoft.Compute/virtualMachines/aks-default-0REDACTED0-0' or the scope is invalid. If access was recently granted, please refresh your credentials."`

So given this error I thought I may want to go do step#6 but then when I run the customized command `az aks show -g <resourcegroup> -n <name> --query servicePrincipalProfile.clientId -o tsv` instead of outputting a UUID for me it just says `msi`

I suppose next Ill just add the role its complaning about now, if it complains again ill add another maybe itll stop complaining.

Hope this helps you devs; I'd really like to get this one up and running

**Comment by aramase** [comment]
The required permissions for MSI cluster are documented here - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.msi.md

Once the required role assignments are done, the MIC pods will need to be restarted to refresh the credentials. Please let me know if you still have any issues after that.

**Comment by tezzigator** [comment]
Thanks - I added the 4 extra roles as directed (the initial 2, the 3rd for a single User Managed identity Im using, and the 4th is since my VNet is in a different RG). and deleted/re-applied the azureidentity, azureidentitybinding, deployment, daemonset, and also all the CustomResourceDefinitions.  Here are my logs from the MIC's:
```
C:\>kubectl logs --tail=500 mic-787488d87b-7lxt6
I0411 00:27:54.047981       1 main.go:79] Starting mic process. Version: 1.5.5. Build date: 2020-01-28-23:11
I0411 00:27:54.048044       1 main.go:98] kubeconfig (/etc/kubernetes/kubeconfig/kubeconfig) cloudconfig (/etc/kubernetes/azure.json)
I0411 00:27:54.049171       1 main.go:109] Client QPS set to: 5. Burst to: 5
I0411 00:27:54.049196       1 mic.go:92] Starting to create the pod identity client. Version: 1.5.5. Build date: 2020-01-28-23:11
I0411 00:27:54.188217       1 mic.go:98] Kubernetes server version: v1.16.7
I0411 00:27:54.188486       1 cloudprovider.go:101] MIC using user assigned identity: ce14##### REDACTED #####d577 for authentication.
I0411 00:27:54.188699       1 log.go:16] Initialized health probe on port &[8080]
I0411 00:27:54.188710       1 log.go:11] Started health probe
I0411 00:27:54.188754       1 log.go:16] Registered views for metric%!(EXTRA *[]interface {}=&[])
I0411 00:27:54.188777       1 log.go:11] Starting Prometheus exporter
I0411 00:27:54.188781       1 log.go:16] Registered and exported metrics on port &[8888]
I0411 00:27:54.188786       1 mic.go:164] Initiating MIC Leader election
I0411 00:27:54.188794       1 leaderelection.go:175] attempting to acquire leader lease  default/aad-pod-identity-mic...
E0411 00:28:12.430824       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on endpoints "aad-pod-identity-mic": the object has been modified; please apply your changes to the latest version and try again

C:\>kubectl logs --tail=500 mic-787488d87b-8bqls
I0411 00:27:54.089008       1 main.go:79] Starting mic process. Version: 1.5.5. Build date: 2020-01-28-23:11
I0411 00:27:54.089052       1 main.go:98] kubeconfig (/etc/kubernetes/kubeconfig/kubeconfig) cloudconfig (/etc/kubernetes/azure.json)
I0411 00:27:54.090121       1 main.go:109] Client QPS set to: 5. Burst to: 5
I0411 00:27:54.090144       1 mic.go:92] Starting to create the pod identity client. Version: 1.5.5. Build date: 2020-01-28-23:11
I0411 00:27:54.186531       1 mic.go:98] Kubernetes server version: v1.16.7
I0411 00:27:54.186866       1 cloudprovider.go:101] MIC using user assigned identity: ce14##### REDACTED #####d577 for authentication.
I0411 00:27:54.187144       1 log.go:16] Initialized health probe on port &[8080]
I0411 00:27:54.187164       1 log.go:11] Started health probe
I0411 00:27:54.187219       1 log.go:16] Registered views for metric%!(EXTRA *[]interface {}=&[])
I0411 00:27:54.187254       1 log.go:11] Starting Prometheus exporter
I0411 00:27:54.187260       1 log.go:16] Registered and exported metrics on port &[8888]
I0411 00:27:54.187265       1 mic.go:164] Initiating MIC Leader election
I0411 00:27:54.187273       1 leaderelection.go:175] attempting to acquire leader lease  default/aad-pod-identity-mic...
I0411 00:28:12.426474       1 leaderelection.go:184] successfully acquired lease default/aad-pod-identity-mic
I0411 00:28:12.527138       1 log.go:11] CRD informers started
I0411 00:28:12.527182       1 pod.go:73] Pod cache synchronized. Took 100.189817ms
I0411 00:28:12.527364       1 pod.go:80] Pod watcher started !!
I0411 00:28:12.527436       1 mic.go:257] Sync thread started.
```

NMI logs:
```
C:\>kubectl logs nmi-52hmm
time="2020-04-11T00:38:42Z" level=info msg="Starting nmi process. Version: 1.5.5. Build date: 2020-01-28-23:10. Log level: info."
time="2020-04-11T00:38:43Z" level=info msg="CRD lite informers started "
time="2020-04-11T00:38:43Z" level=info msg="Initialized health probe on port &[8080]"
time="2020-04-11T00:38:43Z" level=info msg="Started health probe"
time="2020-04-11T00:38:43Z" level=info msg="Registered views for metric%!(EXTRA *[]interface {}=&[])"
time="2020-04-11T00:38:43Z" level=info msg="Starting Prometheus exporter"
time="2020-04-11T00:38:43Z" level=info msg="Registered and exported metrics on port &[9090]"
time="2020-04-11T00:38:43Z" level=info msg="Listening on port 2579"
time="2020-04-11T00:38:43Z" level=warning msg="Flushing iptables to add aad-metadata custom chains"
time="2020-04-11T01:05:37Z" level=error msg="no AzureAssignedIdentity found for pod:kube-system/omsagent-rs-79d5df4b5c-wkz8c in assigned state, context canceled" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.0.0.23
time="2020-04-11T01:05:37Z" level=info msg="Status (404) took 60051740597 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.0.0.23
time="2020-04-11T01:06:29Z" level=error msg="no AzureAssignedIdentity found for pod:kube-system/omsagent-q6qkc in assigned state, context canceled" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.0.0.33
```
There are a lot of regular-occuring 404's in the NMI logs, from 2 remote clients Im not really sure who they are.  Also when I do a `curl -H "Metadata: true" 169.254.169.254/metadata/instance?api-version=2019-11-01` from a pod that I selector-matched with `aadpodidbinding` the NMI shows a 200OK in its logs `time="2020-04-11T03:45:02Z" level=info msg="Status (200) took 3584423 ns" req.method=GET req.path=/metadata/instance req.remote=10.0.0.34` so it at least it looks like the iptables/chains part is working.

**Comment by aramase** [comment]
@tezzigator The 404 error is for oms agent pod running on your cluster. Once pod-identity is installed, all applications/pods running on the nodes that use MSI will go through the pod-identity validation. As there is no AzureIdentity and AzureIdentityBinding for the oms pod, it's failing to fetch token. If there are applications on the cluster which still needs to use MSI but not go through pod-identity validation, then you can create `AzurePodIdentityException` - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.app-exception.md

**Comment by tezzigator** [comment]
ah thanks - I should have realized that, yes I have 3 MSIs there in my RG, also I have the kubelet's identity as well I think Ill have to deal with for creating resources, I'll have to deal with that part later.

For now - I've got my worker pod that is attempting to access a keyvault.  It has the aadpodidbinding label that matches in my YAML file for AzureIdentity/Binding. (and for now I'm developing everything in the default namespace).  When my worker pod spins up theres no log activity in the mic pods but the nmi pod has this for my pod's IP:
```
time="2020-04-13T19:25:43Z" level=warning msg="parameter resource cannot be empty" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.10.10.x
time="2020-04-13T19:25:43Z" level=info msg="Status (400) took 56600 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.10.10.x
```

**Comment by aramase** [comment]
@tezzigator The resource header needs to be set while making a request to fetch the token. If it doesn't exist, then metadata endpoints fails to return a token. See these examples where resource is set for each token request - https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#overview.

Also, the aadpodidbinding needs to be in the `spec.template.metadata.labels` in the deployment and `metadata.labels` for pods. If you don't see any logs for the pod in MIC,  then it's possible-

1. AzureIdentityBinding referring to wrong AzureIdentity
2. The label is not set as expected

Let me know if this helps debug!

**Comment by tezzigator** [comment]
I really appreciate your help.  Ill look at the resource header in a bit (this all works locally, so not sure why its not working on AKS)

I have a [gist](https://gist.github.com/tezzigator/e6595e6af8e4d44dc8a7c4b7945d3995) with my YAML.  I 100% verified the ResourceID and ClientID of my identity is correct in that YAML.

I have also put in the 4 role assignments:
```
  az role assignment create --role "Virtual Machine Contributor" --assignee REDACTED  --scope /subscriptions/REDACTED/resourceGroups/CLUSTERRG
   az role assignment create --role "Managed Identity Operator" --assignee REDACTED   --scope /subscriptions/REDACTED/resourceGroups/CLUSTERRG
   az role assignment create --role "Managed Identity Operator" --assignee REDACTED    --scope /subscriptions/REDACTED/resourceGroups/CLUSTERRG
   az role assignment create --role "Virtual Machine Contributor" --assignee REDACTED    --scope /subscriptions/REDACTED/resourceGroups/CLUSTERRG
```
  
However it may be the wrong assignee and/or the wrong RG  there.  Should I use the cluster's kubelet's system managed identity?  and for that ResourceID of the RG, should I use the one the cluster itself is in, or the one that was created to put all the cluster componenents in?
