### ISSUE TITLE
AzureAssignedIdentity  created in the wrong namespace

### ISSUE THREAD

**Issue by aelmanaa** [Azure/aad-pod-identity#607]
Hello 

I created "AzureIdentity" & "AzureIdentityBinding" in a given namespace . Everything is working fine but I noticed that another resource was created automatically "AzureAssignedIdentity" and was created in "default" namespace.

Is behaving as expected? In my case, i'd like to scope azureidentity by namespace as we have several teams sharing the same cluster and each team has its own namespace.

thanks a lot

**Comment by ezYakaEagle442** [comment]
Agreed, it would make sens to have azureassignedidentities created into the same NS where the identity & binding were created

```sh
k get azureidentity -A
k get azureidentitybindings -A
k get azureassignedidentities -A

k get azureidentity -n $target_namespace
k get azureidentitybindings -n $target_namespace
k get azureassignedidentities # -n $target_namespace

k describe azureidentity $IDENTITY_NAME -n $target_namespace
k describe azureidentitybinding $IDENTITY_NAME-binding -n $target_namespace

for asi in $(k get azureassignedidentities -o custom-columns=:metadata.name)
do
  if [ "$asi" = "$pod-$target_namespace-$IDENTITY_NAME" ]; then
    k describe azureassignedidentities $asi 
  fi
done
```

**Comment by aramase** [comment]
@aelmanaa @ezYakaEagle442 By default aad-pod-identity creates the `AzureAssignedIdentity` in default namespace. However you can run aad-pod-identity in force namespaced mode - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.namespaced.md. When run in force namespaced mode, the `AzureAssignedIdentity` will be created in the same namespace as the `AzureIdentity, `AzureIdentityBinding` and pods. 

This mode is not enabled by default in order to support backward compatibility for users.

**Comment by aelmanaa** [comment]
@aramase thanks for your answer. what does it change functionally to have AzureAssignedIdentity in default namespace rather than AzureIdentity's namespace?
