### ISSUE TITLE
Type upgrade failed when ClientID and Resource ID in AzureIdentity are empty

### ISSUE THREAD

**Issue by chewong** [Azure/aad-pod-identity#612]
https://github.com/Azure/aad-pod-identity/issues/515#issuecomment-625140220

**Comment by aramase** [comment]
This is a valid error. The `resourceID` and `clientID` are defined as an array `{}`, but `clientID` and `resourceID` are of type string. If type upgrade fails for 1.6.0, then the MIC pod shouldn't start because 1.6.0 MIC will not work with the old `AzureIdentity` and `AzureIdentityBinding` with wrong case.
