### ISSUE TITLE
AAD pod identity vs AKS MSI

### ISSUE THREAD

**Issue by jefjos** [Azure/aad-pod-identity#653]
I ask this question for my understanding. 
Suppose I deploy MIC and NMI in AKS cluster.
I bind pod with label = label1 to an azure identity.
I do not create a binding for pod with label = label2

Now if I access IMDS endpoint from pod with label = label1 I understand I will get the token for the assigned identity.

If I access IMDS endpoint from pod with label = label2, will I get an error? Since I have not assigned an identity.

**Comment by chewong** [comment]
Hey @jefjos. By default, IMDS requests will be routed to NMI. Since the second pod doesn't have an identity assigned to it, it will not be able to get a token from IMDS. Though you can create an exception to that. See https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.app-exception.md.

**Comment by jefjos** [comment]
Thanks @chewong
