### ISSUE TITLE
Using VMSS for AKS - issue 339 has resurfaced

### ISSUE THREAD

**Issue by oliverholliday** [Azure/aad-pod-identity#692]
I filed bug 339 about a year ago and we've been using aad-pod-identity successfully ever since. 

We've since moved to using VMSS for AKS and this same bug has re-surfaced - aad-pod-identity on our cluster was sat unable to bind any pod identities because Azure was throwing an error about invalid scopes.

Logs from MIC showed it was attempting to bind lots of things at once, but some of them were invalid. 

```
mic E0720 15:43:58.683557 1 mic.go:848] Applying binding test2-crypto-9sqpei8f node aks-aksagentpool-34621003-vmss000000 for pod test2-reader-dzyy0hyg-7b6cfdbf9c-r5xpp-test2-test2-crypto-6bql77oc resulted in error compute.VirtualMachineScaleSetsClient#CreateOrUp │
│ date: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client '9b0884b9-a85e-48b6-86df-d535470a7655' with object id '9b0884b9-a85e-48b6-86df-d535470a7655' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/1285-4dfb-8c78-76279ea330dd/resourceGroups/MC_deveu_deveu2_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-aksagentpool-34621003-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/e3e25af1-1285-4dfb-8c78-76279ea330dd/resourcegroups/deveu/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test3-reader,/subscriptions/e3e25af1
<snip>
```

The identity test3-reader no longer exists at all, and in the output for `az vmss show` I could see all the old identities were still bound but invalid:

```
        "/subscriptions/1285-4dfb-8c78-76279ea330dd/resourcegroups/deveu/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test3-reader": {
          "clientId": null,
          "principalId": null
        },
```

_Originally posted by @oliverholliday in https://github.com/Azure/aad-pod-identity/issues/339#issuecomment-661127095_

**Comment by aramase** [comment]
@oliverholliday MIC uses the `AzureIdentity` to determine which all identities need to be assigned. It looks like there is still an `AzureIdentity in the cluster that's referencing the identity that no longer exists `test2-reader-dzyy0hyg-7b6cfdbf9c-r5xpp-test2-test2-crypto-6bql77oc` - pod name (`test2-reader-dzyy0hyg-7b6cfdbf9c-r5xpp`), namespace (`test2`), AzureIdentity (`test2-crypto-6bql77oc`). If you delete the `AzureIdentity` that's no longer required then you wouldn't see the error.

**Comment by oliverholliday** [comment]
That AzureIdentity does exist and is needed, but the one referenced later in the same error message - test3-reader - doesn't exist either as an AzureIdentity resource or as a ManagedIdentity in Azure itself.

Once I went to the Azure VMSS UserAssignedIdentities UI and deleted all of the invalid ones MIC kicked back into gear and successfully bound all of our test1* and test2* identities. 

To clarify, I didn't change anything in the cluster at all - I had to manually change the Azure VMSS identity bindings to get it to start working again.

**Comment by aramase** [comment]
Which version of `aad-pod-identity` are you using?

**Comment by oliverholliday** [comment]
1.5.5 of MIC and NMI

**Comment by aramase** [comment]
Thank you! We have made major changes in 1.6+ to 

- Switch to using the `PATCH` API for assigning identities instead of `CreateOrUpdate`.  In case of `CreateOrUpdate`, the current identity list on the VMSS is fetched, new identities appended and then a `PUT` request is made. In case an old identity exists on the VMSS which no longer exists in azure, that would result in the error you're observing. With `PATCH` we only send a map of identities to assign/delete which doesn't interfere with the already existing identities on the VMSS. 
- Added finalizer for `AzureAssignedIdentity` to ensure the identities are successfully un-assigned from the VMSS if the namespace containing the `AzureIdentity` and `AzureIdentityBinding` are deleted. 

Please try out the latest version and let us know if you're having issues. Review this doc for breaking changes before upgrade to 1.6+ - https://github.com/Azure/aad-pod-identity#v160-breaking-change

**Comment by oliverholliday** [comment]
Ah sorry about that, I did skim the changelog but couldn't see anything specific!

I'll try it out and get back to you if it's still broken.
