### ISSUE TITLE
Pod is started before identity is assigned and authentification fails

### ISSUE THREAD

**Issue by kutsyk-neocles** [Azure/aad-pod-identity#738]
Our code is using assigned identity to connect to Azure KeyVault.

From time to time when we redeploy fresh version of the code it fais to connect, writes that there are missing env variables for Azure KeyVault.

After restarting pod(deleting) the one can connect or not, it depends. 
We found out that each time on pod destruction and creating object `AzureAssignedIdentity` object is recreated and there is a status Assigned if everything is fine.

Is there a way to automate pod startup only when that object has proper status?

**Comment by chewong** [comment]
Hey @kutsyk-neocles, it takes time for a user-assigned identity to get assigned to the underlying node where the pod is running (10-20s for a VM node, 30-40s for a VMSS node), so there might be a brief window between when your app started running and the identity gets assigned, where your app will fail to acquire a token. Since the SDK failed to acquire a token, it falls back to using env variables for authentication.

You can solve this by:

- having a retry logic in your app for acquiring the token
- having an init container to check for identity assignment

**Comment by kutsyk-neocles** [comment]
Hey @chewong is there an init container for this, or should we create one by ourselves?

**Comment by chewong** [comment]
We currently don't have an init container for such a scenario, but I'd imagine the init container would be a simple curl to the IMDS endpoint 169.256.169.256 until it returns a 200. See https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service#accessing-azure-instance-metadata-service for more details.

**Comment by kutsyk-neocles** [comment]
Hm, that doesn't look proper. 
Does it mean we should now work with another server and pay for its availability? 
What is a plan for making correct flow for it or exposing some status which can be used with initContainer?

**Comment by chewong** [comment]
169.256.169.256 is a well-known IP address that can be accessed only from within the Azure VM instance (instance metadata service or IMDS). You don't have to pay for it. Pod identity obtains a token through http://169.254.169.254/metadata/identity/oauth2/token using the user-assigned identity you bound to your pod and return it to the pod. Now, since there is a delay between when your app started running and the identity gets assigned, by the time your init container is able to obtain a token, that implies that your application will have access to the token. Here is an example of an init container you can try:
```
      initContainers:
        - name: init
          image: mcr.microsoft.com/azure-cli
          command:
            - sh
            - -c
            - az login --identity
```

I can definitely add some documentation for such scenario.

**Comment by chewong** [comment]
@kutsyk-neocles any update on this issue?

**Comment by kutsyk-neocles** [comment]
Yeah, we didn't go that way as it requires over-engineering simple thing, instead we just implemented retry in our code

**Comment by chewong** [comment]
Sounds good. Closing this issue for now but feel free to open a new issue if you have any questions.
