### ISSUE TITLE
NMI probes not using http codes

### ISSUE THREAD

**Issue by Mandur** [Azure/aad-pod-identity#739]
Hello,

**Describe the bug**
When experimenting with the NMI liveness probes I noticed the [code](https://github.com/Azure/aad-pod-identity/blob/9af68e1addf8a52b5183e5d7f611ed030cc1341f/pkg/probes/probes.go#L15) was not using HTTP error codes to report pod unavailability but rather relied on a "Active" / "Not Active" content as part the answer.

**Expected behavior**
I would have expected that any HTTP code >= 200 and <400 would indicate success and rest would indicate failure as described [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request).  Is there a special reason for the current way of working?

Thanks!

**Comment by aramase** [comment]
@Mandur Thank you for opening the issue 👍 

I believe the reason was for common probe for both NMI and MIC. The status is `200 OK` as soon as the probe server is up and running. `Active/Not Active` provide more detail on the current state of MIC/NMI. In case of MIC, one of the pod is a leader and the other one is backup. In case of MIC, it would always be a `200 OK` so that the backup can keep trying to acquire the leader lease. Hope that clarifies it? Let us know what you think.

**Comment by Mandur** [comment]
Thank you for the quick answer, that make sense. Do I understand correctly that then the NMI probes should never return 'Not Active', but either return 'Active', either timeout?

**Comment by aramase** [comment]
>  Do I understand correctly that then the NMI probes should never return 'Not Active', but either return 'Active', either timeout

That's right. NMI should always return `Active` or fail to respond. Only if the iptable rules have been successfully added will NMI respond with `Active` status.

**Comment by Mandur** [comment]
Thank you for the information, that make sense, I will close the issue
