### ISSUE TITLE
AAD Pod Identity - Need for further clarity on documentation

### ISSUE THREAD

**Issue by abarrionuevodevops** [Azure/aad-pod-identity#852]
Hello
I need you guys to clarify the guidelines in the documentation.
This article https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough/ states "Important: For AKS clusters with limited egress traffic, Please install aad-pod-identity in kube-system namespace using the helm charts."

On the other hand, this article https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes does not lead to deploy in the kube-system namespace.

An this Github article itself in fact when using the deployment.yaml for  an RBAC-enabled AKS cluster (https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml) doesn't deploy to the kube-system namespace.

I've deployed with the helm chart in the default namespace on an RBAC-enabled private cluster with limited egress traffic, and the deployment seems to work fine.

So I need you guys to please specify what is the basis for the statement I wrote above between quotes. What we loose or what risks may be there when deploying with the helm chart on an RBAC-enabled private AKS cluster on the default namespace instead of on the kube-system namespace

**Comment by aramase** [comment]
@abarrionuevodevops Thank you for opening the issue 👍 

> So I need you guys to please specify what is the basis for the statement I wrote above between quotes. What we loose or what risks may be there when deploying with the helm chart on an RBAC-enabled private AKS cluster on the default namespace instead of on the kube-system namespace

The recommendation in deploy in `kube-system` namespace was because there was an issue with AKS where the `KUBERNETES_HOST` env variable injected in pods for non `kube-system` namespace was the API server IP. For limited egress using the IP to connect to the API server will result in SNI TLS failure errors. However in `kube-system` namespace, AKS injects the API server fqdn as `KUBERNETES_HOST` which resolves the issue.

Ref: https://github.com/Azure/aad-pod-identity/issues/467

**Comment by abarrionuevodevops** [comment]
Thanks for the quick and precise response
