### ISSUE TITLE
VMSS Azure-Pod Integration Documents

### ISSUE THREAD

**Issue by JESWINKNINAN** [Azure/aad-pod-identity#855]
Any document which refers to VMSS Azure AAD Pod Identity Integrations

**Comment by aramase** [comment]
@JESWINKNINAN aad-pod-identity should work with no additional configuration for VMAS/VMSS. The required role assignments for different auth modes are documented here - https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/

You can try out the demo - https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough/

**Comment by JESWINKNINAN** [comment]
gotcha, Thanks

**Comment by JESWINKNINAN** [comment]
I am facing an issue while testing with VMSS nodes. When I have created AzureIdentity and its binding and make a pod to schedule to one of the nodes under the VMSS, it shows that it is not able to  because of the node not found 

 failed to update user-assigned identities on node test-poc-k8s-node-1 (add [1], del [0], update[0]), error: failed to get identity resource, error: failed to get vm test-poc-k8s-node-1 in resource group myrg, error: failed to get vmtest-poc-k8s-node-1 in resource group myrg, error: compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Compute/virtualMachines/test-poc-k8s-node-1' under resource group 'myrg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

As per the docs: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-instance-ids#scale-set-vm-names the scale set VM name is strictly followed as {scale-set-name}_{instance-id}. And when we join this node to a cluster with same name it has will throws the error since Kubernetes doesn't support that:

A bit of confusion have got occurred here

**Comment by chewong** [comment]
It looks like MIC is using a VM client instead of VMSS client to get the VMSS instance. How are you creating your nodes? Is it through Azure portal/azure-cli? AAD Pod Identity chooses one of VM and VMSS client based on the  [ProviderID](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#nodespec-v1-core) from NodeSpec (in the form of `/subscriptions/<SubscriptionID>/resourceGroups/<ResourceGroup>/providers/Microsoft.Compute/virtualMachineScaleSets/<VMSSName>/virtualMachines/0`). If you are creating your own node and joining it to your cluster, could you ensure you have that field correctly populated?

**Comment by JESWINKNINAN** [comment]
@chewong This looks good, there was some issue with controller manager which was not configuring Provider ID to VMSS instances.
