### ISSUE TITLE
Deploy AAD Pod Identity in a Cluster with Kubenet

### ISSUE THREAD

**Issue by V4A001** [Azure/aad-pod-identity#949]
Sorry, I am not an expert in Kubernetes, I just want to code and have it secure. So I want to use a azure key vault through code. With azure app service this easy, with K8 it become more like being a system administrator looking into issue after issue for days. I even checked how Google is doing this (even more horrible by the way).

I believe K8 is over complicated which is emphasized by mismatching documentation and chunks of related code not working together as seen a lot in open source projects. That why I like the .NET frameworks a lot: just 1 place for documentation and easy to use and now even 1 library .net5 for all.

As said I have a K8 cluster running. I want to add a managed identity as with app services to get hold of a azure key vault. I followed a lot of different articles and I am able to use CLI to create all. I run into this error which is introduced because of a vulnerability: https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-1677 .

AAD Pod Identity is not supported for Kubenet. Review https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/

The guide lines in the documentation are too hard to follow to understand what is required. If I install the agent, the rest of the AAD deployment fails and hangs on 'pending' (the mic-token and nmi-token pods). And I am actually forced and drawn into more complicated stuff around K8 like this OPA....more system admin work. He, I just want to code functional stuff!

So after two days of uncompleted work not getting this to work, I will start deploying the AKS with --network-plugin azure instead of Kubenet. No line of code written yet to do something with azure key vault :-(

I saw an easier way is on the way in a preview: https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity#before-you-begin) . Hope it will make live easier. How it is now is just frustrating.

.

**Comment by V4A001** [comment]
Check this post why deployment or service are more common than pod:
https://stackoverflow.com/questions/41325087/what-is-the-difference-between-a-pod-and-a-deployment#:~:text=Both%20Pod%20and%20Deployment%20are,for%20a%20production%20use%2Dcase.

**Comment by aramase** [comment]
@V4A001 Thank you for the feedback.

The pod identity being disabled in Kubenet was to address a security concern with network plugin Kubenet. We tried to add as much detail as possible to the docs so users take necessary precautions while enabling it in a cluster with kubenet. If you wish to install, then you can use the helm configuration `nmi.allowNetworkPluginKubenet=true` and that should enable pod identity. Since pod identity is an add-on to an existing cluster, these are things that would require manual configuration and can't be automated from  pod identity spec.

> I saw an easier way is on the way in a preview: https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity#before-you-begin) . Hope it will make live easier. How it is now is just frustrating.

The preview feature is available for AKS and you can give it a try. Support for managed pod identity with AKS was rolled out recently and you should be able to enable it.

We'll take the feedback and try to make it more simpler as we continue to make changes and design v2.

Closing this issue now. Please feel free to open a new issue if you've any questions.
